import Home from "./Home";
import SignIn from "./signin";
import SignUp from "./signup";
import NotFound from "./404";
import DiseaseSlider from "./awareness";
import HealthCalculator from "./healthcalculator";
import CommunityForum from "./community";
import TravelingDoctors from "./traveling-doctors";
import UserProfilePage from "./UserProfilePage";
import ResultsPage from "./ResultsPage";
export { Home, SignIn, SignUp, NotFound,DiseaseSlider,HealthCalculator,CommunityForum,TravelingDoctors,UserProfilePage,ResultsPage};
